#!/usr/bin/env bash
HEADER_ENABLED=false

if "$HEADER_ENABLED"; then
   MAIN_DOTGO_HEADER=$(head -n 4 main.go)
   MAIN_DOTGO_BODY=$(tail -n +5 main.go)
   echo "$MAIN_DOTGO_BODY" > main.go
fi

gofmt -w "$PWD" # format and organize imports

if "$HEADER_ENABLED"; then
   MAIN_DOTGO_BODY=$(cat main.go)
   echo "$MAIN_DOTGO_HEADER" > main.go
   echo "" >> main.go # add missing newline
   echo "$MAIN_DOTGO_BODY" >> main.go
fi

for x in "$PWD"/*.go; do
   echo "Formatted $(basename "$x")"
done
